exhaust/exogram/urls.py
from django.urls import path

from exhaust.exogram import views

app_name = 'exogram'

urlpatterns = [
    path('', views.GramListView.as_view(), name='gram_list'),
    path('<str:public_id>/', views.GramDetailView.as_view(), name='gram_detail'),
    path('<str:public_id>/<slug:slug>/', views.GramDetailView.as_view(), name='gram_detail'),
]

exhaust/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('page/<int:page>/', views.PostListView.as_view(), name='post_list'),
    path('category/<slug:category>/', views.PostCategoryListView.as_view(), name='post_category_list'),
    path('category/<slug:category>/page/<int:page>/', views.PostCategoryListView.as_view(), name='post_category_list'),
    path('category/<slug:category>/feed/', views.PostCategoryFeedView.as_view(), name='post_category_feed'),
    path('feed/', views.PostFeedView.as_view(), name='post_feed'),
    path('post/<int:identifier>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:identifier>/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    # Media upload stuff for the admin.
    path('image-upload/', views.ImageUploadView.as_view(), name='image_upload'),
    path('image-redirect/<int:pk>/', views.ImageRedirectView.as_view(), name='image_redirect'),
]

exhaust/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import TemplateView
from markdownx.views import MarkdownifyView

from exhaust.posts.sitemaps import POSTS_SITE_MAPS

urlpatterns = [
    path('', include('exhaust.posts.urls', namespace='posts')),
    path('exogram/', include('exhaust.exogram.urls', namespace='exogram')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('admin/', admin.site.urls),
    path('markdownx/markdownify/', MarkdownifyView.as_view(), name='markdownx_markdownify'),
    path('sitemap.xml', sitemap, {'sitemaps': POSTS_SITE_MAPS}, name='django.contrib.sitemaps.views.sitemap'),
    # Error page styling tests. It's OK to have these outside of DEBUG (if
    # someone wants to pretend they're having a 500 they're more than welcome
    # to). It means there's one less branch to test in settings.
    path('404/', TemplateView.as_view(template_name='404.html')),
    path('500/', TemplateView.as_view(template_name='500.html')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

exhaust/common/models.py
from django.db import models
from django.utils import timezone


class PublishedModelQuerySet(models.QuerySet):
    '''
    A manager that allows some crude version of "draft" and a "post queue"
    by excluding anything with online=False or a date set to the future.
    '''

    def select_published(self):
        return self.filter(
            online=True,
            # Swapping out the seconds and microseconds to 0 means that the
            # same query is generated for any particular minute in the day.
            # This is much more query-caching (i.e. cachalot) friendly, in
            # both that the same query will be generated for one minute, and
            # stops the cache filling up with entries that will never get a
            # hit.
            date__lte=timezone.now().replace(second=0, microsecond=0),
        )


class PublishedModel(models.Model):
    objects = models.Manager.from_queryset(PublishedModelQuerySet)()

    date = models.DateTimeField(
        default=timezone.now
    )

    online = models.BooleanField(
        default=False,
        help_text='Uncheck this to hide this post on the frontend.'
    )

    class Meta:
        abstract = True

exhaust/exogram/models.py
import secrets
from datetime import datetime

from django.db import models
from django.urls import reverse
from markdownx.models import MarkdownxField

from exhaust.common.models import PublishedModel


class Gram(PublishedModel):
    # `public_id` will be auto-generated on save. It's a six-character random
    # string, which might be enough to prevent object enumeration, for anyone
    # but the most bored.
    public_id = models.CharField(
        max_length=8,
    )

    slug = models.SlugField(
        blank=True,
        help_text='Use this to optimise the URL for search engines.',
    )

    image = models.ImageField()

    text = MarkdownxField(null=True, blank=True)

    commons_link = models.URLField(
        'Wikimedia Commons link',
        blank=True,
    )

    class Meta:
        ordering = ['-date']

    def __str__(self):
        parts = [datetime.strftime(self.date, '%Y-%m-%d')]

        if self.text:
            if len(self.text) > 60:
                parts.append(self.text[:57] + '...')
            else:
                parts.append(self.text)

        return ': '.join(parts)

    def save(self, *args, **kwargs):
        if not self.public_id:
            self.public_id = secrets.token_urlsafe(6)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        if self.slug:
            return reverse(
                'exogram:gram_detail',
                kwargs={'public_id': self.public_id, 'slug': self.slug}
            )
        return reverse('exogram:gram_detail', kwargs={'public_id': self.public_id})

    def detail_pagination(self):
        pagination = {}
        for key, attribute in [('newer', 'get_next_by_date'), ('older', 'get_previous_by_date')]:
            try:
                pagination[key] = getattr(self, attribute)().get_absolute_url()
            except self.DoesNotExist:
                pagination[key] = None
        return pagination

exhaust/posts/forms.py
from django.forms import ModelForm

from .models import PostImage


class ImageUploadForm(ModelForm):
    class Meta:
        fields = ['image']
        model = PostImage

exhaust/common/views.py
class PublishedModelViewMixin:
    def get_queryset(self):
        queryset = super().get_queryset()
        # Allow staff users (me) to view unpublished things to see what they
        # will look like on the front end.
        if not self.request.user.is_staff:
            queryset = queryset.select_published()
        return queryset

exhaust/exogram/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import Http404
from django.views.generic import DetailView, ListView

from exhaust.common.views import PublishedModelViewMixin
from exhaust.exogram.models import Gram


class GramMixin(PublishedModelViewMixin, UserPassesTestMixin):
    def test_func(self):
        # gate this on the user being me, for now
        return self.request.user.is_superuser


class GramListView(GramMixin, ListView):
    model = Gram


class GramDetailView(GramMixin, DetailView):
    model = Gram

    def get_object(self, queryset=None):
        # Re-implementation of the Django default get_object, which cannot
        # handle two arguments when one of the arguments is not `pk`.
        try:
            return self.get_queryset().get(public_id=self.kwargs['public_id'])
        except self.model.DoesNotExist:
            raise Http404(f'{self.model._meta.verbose_name.capitalize()} not found.')  # pylint:disable=raise-missing-from

exhaust/posts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import DetailView, FormView, ListView, RedirectView

from exhaust.common.views import PublishedModelViewMixin
from exhaust.posts.forms import ImageUploadForm
from exhaust.posts.models import Category, Post, PostImage


class PostViewMixin(PublishedModelViewMixin):
    model = Post


class PostListView(PostViewMixin, ListView):
    paginate_by = 8

    def get(self, request, *args, **kwargs):
        # For old pagination compatibility: redirect '?page=1' to '/page/1/'
        if 'page' in request.GET:
            kwargs['page'] = request.GET['page']
            return redirect(
                reverse(f'{request.resolver_match.namespace}:{request.resolver_match.url_name}', kwargs=kwargs),
                permanent=True,
            )
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        # Prefetch categories so we have a single query for loading categories,
        # rather than N queries for N posts.
        queryset = super().get_queryset().prefetch_related('categories')

        if self.kwargs.get('category'):
            queryset = queryset.filter(categories__slug=self.kwargs['category']).distinct()
        return queryset


class PostCategoryListView(PostListView):
    template_name = 'posts/post_category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['object'] = get_object_or_404(Category, slug=self.kwargs['category'])
        return context


class PostDetailView(PostViewMixin, DetailView):
    def get(self, request, *args, **kwargs):
        # If the path does not match the canonical URL of the post, then
        # redirect. This handles two situations:
        #
        # 1) that we create a post, add a slug later. We could end up with
        #    two possible URLs for it, e.g. /post/42/ and /post/42-some-slug/,
        #    which we don't really want.
        #
        # 2) that some genius decides to change the second URL above to
        #    /post/42-something-unpleasant/ and it looks like we created that
        #    URL.

        obj = self.get_object()

        if not request.path == obj.get_absolute_url():
            return redirect(obj.get_absolute_url(), permanent=True)
        return super().get(request, args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['detail_page'] = True
        return context

    def get_object(self, queryset=None):
        # Re-implementation of the Django default get_object, which cannot
        # handle two arguments when one of the arguments is not `pk`.
        try:
            return self.get_queryset().get(identifier=self.kwargs['identifier'])
        except self.model.DoesNotExist:
            raise Http404(f'{self.model._meta.verbose_name.capitalize()} not found.')  # pylint:disable=raise-missing-from


class BasePostFeedView(PostListView):
    '''An RSS feed for all posts.

    This would, in an idea world, work with Django's feed module. But that API
    is a mess for the common use case of generating a human-readable RSS feed
    to plug in to a reader, as well as looking absolutely nothing like any of
    Django's generic views.
    '''

    template_name = 'posts/post_feed.html'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        # allow previewing in DEBUG mode
        if settings.DEBUG and 'debug' in request.GET:
            response['Content-Type'] = 'text/plain; charset=utf-8'
        else:
            response['Content-Type'] = 'application/rss+xml; charset=utf-8'

        return response


class PostFeedView(BasePostFeedView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['feed_title'] = settings.SITE_NAME
        return context


class PostCategoryFeedView(BasePostFeedView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        category = get_object_or_404(Category, slug=self.kwargs['category'])
        context['feed_title'] = f'{category} - {settings.SITE_NAME}'
        return context


class ImageRedirectView(LoginRequiredMixin, RedirectView):
    '''
    A view that redirects to an image, based on its ID. This uses
    LoginRequiredMixin as it is *only* intended to be used for previewing
    Markdown in the admin. When said markdown is rendered on the front end
    the image will be rendered via a different means (extract the PK from the
    URL, then render it in a bunch of sizes). We don't want to do that in the
    admin because it's quite expensive the first time.
    '''
    def get_redirect_url(self, *args, **kwargs):
        return PostImage.objects.get(pk=self.kwargs['pk']).image.url


class ImageUploadView(LoginRequiredMixin, FormView):
    '''
    A replacement for MarkdownX's upload view. Rather than saving it directly
    to storage, it will store it to the PostImage model.
    '''
    form_class = ImageUploadForm

    def form_invalid(self, form):
        response = JsonResponse({
            'image': 'Image missing or broken.',
        })
        response.status_code = 400
        return response

    def form_valid(self, form):
        form.save()
        return JsonResponse({
            'image_code': f'![]({form.instance.get_absolute_url()})'
        })

exhaust/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="LeuIuUyPpFkUmbRYvfIYrYxTXTyto9r2L_jao7aeEiI">
    <meta name="msvalidate.01" content="D273A4B7B5E81E588C2F3B860C27A916">
    <link rel="stylesheet" href="{% static 'build/webpack/style.css' %}?last={{ settings.GIT_COMMIT_HASH }}">

    {% block meta %}{% endblock %}
    <title>{% block title %}{{ settings.SITE_NAME }} - {{ settings.SITE_DESCRIPTION }}{% endblock %}</title>

    {% block extra_head %}{% endblock %}
  </head>

  <body class="layout__body">
    <header class="header">
      <div class="header__inner">
        {% url 'posts:post_list' as homepage_url %}
        {% if request.path == homepage_url %}
          <h1 class="header__masthead">
        {% else %}
          <div class="header__masthead">
        {% endif %}
          <a href="/" class="header__masthead-link">
            <div class="header__title">
              {{ settings.SITE_NAME }}
            </div>

            <div class="header__subtitle">
              {{ settings.SITE_DESCRIPTION }}
            </div>
          </a>
        {% if request.path == homepage_url %}
          </h1>
        {% else %}
          </div>
        {% endif %}

        {% if request.user.is_superuser %}
          <div class="header__navigation">
            <nav class="navigation">
              <ul class="navigation__items">
                <li class="navigation__item">
                  <a href="{% url 'posts:post_list' %}" class="navigation__item-link">posts</a>
                </li>

                <li class="navigation__item">
                  <a href="{% url 'exogram:gram_list' %}" class="navigation__item-link">random acts of image</a>
                </li>
              </ul>
            </nav>
          </div>
        {% endif %}
      </div>
    </header>

    <div class="layout__main">
      {% block main %}{% endblock %}
    </div>


    <footer class="layout__footer">
      <div class="footer">
        <div class="footer__inner">
          <p class="footer__block">
            I'm Lewis, a software engineer by day, petrolhead & cat fan by night.
            You can <a href="/post/2105744346/hello-world/">read what this blog is about</a>.
            Or you can look at <a href="https://lewiscollard.com">what else I get up to</a>.
            Or maybe you've other things to do today! That's fine too. ❤️
          </p>

          <p class="footer__block">
            Email is always <a href="mailto:lewis@lewiscollard.com">warmly welcomed</a>.
          </p>

          <p class="footer__block">
            The source code for this website <a href="https://github.com/lewiscollard/exhaust">is available</a>.
          </p>

          <p class="footer__block">
            Copyright &copy; Lewis Collard, 2020-2024. Anyone caught copying
            any of my photographs or text will be considered a mighty good
            friend of mine.
          </p>
        </div>
      </div>
    </footer>

    <script src="{% static 'build/webpack/main.js' %}"></script>
  </body>
</html>

exhaust/templates/error_base.html
<!doctype html>
<html>
  {% load static %}
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'build/webpack/error-styles.css' %}?last={{ settings.GIT_COMMIT_HASH }}">
  </head>

  <body>
    <div class="error-page">
      <div class="error-page__inner">
        <div class="error-page__header">
          <h1 class="error-page__title">
            <span class="error-page__title-number">{% block number %}{% endblock %}:</span>
            <span class="error-page__title-description">{% block description %}{% endblock %}</span>
          </h1>

          <p class="error-page__text">
            {% block text %}{% endblock %}
          </p>

          <p class="error-page__link-wrap">
            <a href="{% block link %}{% endblock %}">{% block link_text %}{% endblock %}</a>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>

exhaust/templates/youtube_video.html
<div class="vue-youtube-mount">
  <youtube-video id="{{ id }}">
    <p class="youtube-video" data-id="{{ id }}">
      <a class="youtube-video__placeholder-link" href="https://www.youtube.com/watch?id={{ url }}">
        Link to embedded video
      </a>
    </p>
  </youtube-video>
</div>