exhaust/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('page/<int:page>/', views.PostListView.as_view(), name='post_list'),
    path('category/<slug:category>/', views.PostCategoryListView.as_view(), name='post_category_list'),
    path('category/<slug:category>/page/<int:page>/', views.PostCategoryListView.as_view(), name='post_category_list'),
    path('category/<slug:category>/feed/', views.PostCategoryFeedView.as_view(), name='post_category_feed'),
    path('feed/', views.PostFeedView.as_view(), name='post_feed'),
    path('post/<int:identifier>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:identifier>/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    # Media upload stuff for the admin.
    path('image-upload/', views.ImageUploadView.as_view(), name='image_upload'),
    path('image-redirect/<int:pk>/', views.ImageRedirectView.as_view(), name='image_redirect'),
]

exhaust/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import TemplateView
from markdownx.views import MarkdownifyView

from exhaust.posts.sitemaps import POSTS_SITE_MAPS

urlpatterns = [
    path('', include('exhaust.posts.urls', namespace='posts')),
    path('exogram/', include('exhaust.exogram.urls', namespace='exogram')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('admin/', admin.site.urls),
    path('markdownx/markdownify/', MarkdownifyView.as_view(), name='markdownx_markdownify'),
    path('sitemap.xml', sitemap, {'sitemaps': POSTS_SITE_MAPS}, name='django.contrib.sitemaps.views.sitemap'),
    # Error page styling tests. It's OK to have these outside of DEBUG (if
    # someone wants to pretend they're having a 500 they're more than welcome
    # to). It means there's one less branch to test in settings.
    path('404/', TemplateView.as_view(template_name='404.html')),
    path('500/', TemplateView.as_view(template_name='500.html')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT
)

exhaust/posts/models.py
import os
import secrets

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from markdownx.models import MarkdownxField

from exhaust.common.models import PublishedModel


class SEOModel(models.Model):
    '''
    Helper model to get SEO fields (common to posts and categories).
    '''
    seo_title = models.CharField(
        'SEO title',
        max_length=60,
        null=True,
        blank=True,
    )

    meta_description = models.TextField(
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True


class Post(PublishedModel, SEOModel):
    '''
    A post on the site.

    The only required field here is the date. That's to allow any kind of post
    (image-only, text-only, title-only). Of course, it would not make sense to
    have a post with no title, text or image set, but that can be enforced in
    the admin.
    '''

    # It is possible to not have a slug if we only have an image. I also want
    # the option to change the slug while keeping a persistent URL (see views
    # for how this works), so I want some kind of persistent identifier, and
    # PKs offend me for irrational reasons. This will be automatically
    # populated when save() is called.
    identifier = models.IntegerField()

    title = models.CharField(
        max_length=280,
        null=True,
        blank=True,
    )

    link = models.URLField(
        null=True,
        blank=True,
    )

    # Optional slug, for nicer URLs.
    slug = models.SlugField(
        null=True,
        blank=True,
    )

    text = MarkdownxField(
        null=True,
        blank=True,
    )

    image = models.ImageField(
        null=True,
        blank=True,
        upload_to='post_images',
    )

    alt_text = models.CharField(
        max_length=1000,
        help_text='This is assistive text for screen readers. This is very important to fill out on image-only posts.',
        null=True,
        blank=True,
    )

    # This will only be me, but for the future who knows?! (foreveralone.png)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT
    )

    categories = models.ManyToManyField(
        'posts.Category',
        blank=True,
    )

    # Open Graph stuff. I don't like Facebook, but their standards for having
    # a title and description and an image are universally adopted. Roll with
    # it.
    opengraph_title = models.CharField(
        verbose_name='title',
        max_length=100,
        blank=True,
    )

    opengraph_image = models.ImageField(
        verbose_name='image',
        null=True,
        blank=True,
        upload_to='opengraph-images'
    )

    opengraph_description = models.TextField(
        verbose_name='description',
        blank=True,
    )

    class Meta:
        ordering = ['-date']

    def __str__(self):
        if self.title:
            return self.title

        if self.text:
            if len(self.text) > 40:
                return f'{self.text[:38]}...'
            return self.text

        if self.image:
            return f'Image post: {self.image.file.name}'

        # Should never happen, but make pylint happy
        return '(Broken post)'

    def save(self, *args, **kwargs):  # pylint:disable=signature-differs
        if not self.identifier:
            # probs enough for now as it's just me
            # (dear future employers: I would never write something this crappy
            # in code I write for you, promise)
            self.identifier = secrets.randbelow(2**31)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        if self.slug:
            return reverse('posts:post_detail', kwargs={'identifier': self.identifier, 'slug': self.slug})
        return reverse('posts:post_detail', kwargs={'identifier': self.identifier})

    def get_title_link_url(self):
        return self.link or self.get_absolute_url()

    @cached_property
    def body_template(self):
        # upgrade this later to handle various different kinds of post
        # layouts
        return 'posts/layouts/post_body.html'

    @cached_property
    def status_text(self):
        if not self.online:
            return 'Draft'
        if self.date > timezone.now():
            return 'Scheduled'
        return 'Published'


class PostImage(models.Model):
    '''
    A model for storing a in-text image. See `ImageUploadView` in views.py;
    this isn't really useful by itself.
    '''

    image = models.ImageField()

    title = models.CharField(
        max_length=100,
        null=True,
        blank=True,
    )

    timestamp = models.DateTimeField(
        auto_now_add=True,
    )

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.title or self.image.file.name

    def get_absolute_url(self):
        return reverse('posts:image_redirect', kwargs={'pk': self.pk})


class Category(SEOModel):
    title = models.CharField(
        max_length=100,
    )

    slug = models.SlugField()

    description = models.TextField(
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ['title']
        # avoid default rendering of "Categorys"
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_category_list', kwargs={'category': self.slug})


class Attachment(models.Model):
    # A model for "I want to do something with a file". I will use it for
    # small locally-hosted videos.

    file = models.FileField(
        upload_to='post-attachments',
    )

    timestamp = models.DateTimeField(
        default=timezone.now,
    )

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return os.path.basename(self.file.name)

exhaust/posts/forms.py
from django.forms import ModelForm

from .models import PostImage


class ImageUploadForm(ModelForm):
    class Meta:
        fields = ['image']
        model = PostImage

exhaust/posts/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import DetailView, FormView, ListView, RedirectView

from exhaust.common.views import PublishedModelViewMixin
from exhaust.posts.forms import ImageUploadForm
from exhaust.posts.models import Category, Post, PostImage


class PostViewMixin(PublishedModelViewMixin):
    model = Post


class PostListView(PostViewMixin, ListView):
    paginate_by = 8

    def get(self, request, *args, **kwargs):
        # For old pagination compatibility: redirect '?page=1' to '/page/1/'
        if 'page' in request.GET:
            kwargs['page'] = request.GET['page']
            return redirect(
                reverse(f'{request.resolver_match.namespace}:{request.resolver_match.url_name}', kwargs=kwargs),
                permanent=True,
            )
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        # Prefetch categories so we have a single query for loading categories,
        # rather than N queries for N posts.
        queryset = super().get_queryset().prefetch_related('categories')

        if self.kwargs.get('category'):
            queryset = queryset.filter(categories__slug=self.kwargs['category']).distinct()
        return queryset


class PostCategoryListView(PostListView):
    template_name = 'posts/post_category_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['object'] = get_object_or_404(Category, slug=self.kwargs['category'])
        return context


class PostDetailView(PostViewMixin, DetailView):
    def get(self, request, *args, **kwargs):
        # If the path does not match the canonical URL of the post, then
        # redirect. This handles two situations:
        #
        # 1) that we create a post, add a slug later. We could end up with
        #    two possible URLs for it, e.g. /post/42/ and /post/42-some-slug/,
        #    which we don't really want.
        #
        # 2) that some genius decides to change the second URL above to
        #    /post/42-something-unpleasant/ and it looks like we created that
        #    URL.

        obj = self.get_object()

        if not request.path == obj.get_absolute_url():
            return redirect(obj.get_absolute_url(), permanent=True)
        return super().get(request, args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['detail_page'] = True
        return context

    def get_object(self, queryset=None):
        # Re-implementation of the Django default get_object, which cannot
        # handle two arguments when one of the arguments is not `pk`.
        try:
            return self.get_queryset().get(identifier=self.kwargs['identifier'])
        except self.model.DoesNotExist:
            raise Http404(f'{self.model._meta.verbose_name.capitalize()} not found.')  # pylint:disable=raise-missing-from


class BasePostFeedView(PostListView):
    '''An RSS feed for all posts.

    This would, in an idea world, work with Django's feed module. But that API
    is a mess for the common use case of generating a human-readable RSS feed
    to plug in to a reader, as well as looking absolutely nothing like any of
    Django's generic views.
    '''

    template_name = 'posts/post_feed.html'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)

        # allow previewing in DEBUG mode
        if settings.DEBUG and 'debug' in request.GET:
            response['Content-Type'] = 'text/plain; charset=utf-8'
        else:
            response['Content-Type'] = 'application/rss+xml; charset=utf-8'

        return response


class PostFeedView(BasePostFeedView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['feed_title'] = settings.SITE_NAME
        return context


class PostCategoryFeedView(BasePostFeedView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        category = get_object_or_404(Category, slug=self.kwargs['category'])
        context['feed_title'] = f'{category} - {settings.SITE_NAME}'
        return context


class ImageRedirectView(LoginRequiredMixin, RedirectView):
    '''
    A view that redirects to an image, based on its ID. This uses
    LoginRequiredMixin as it is *only* intended to be used for previewing
    Markdown in the admin. When said markdown is rendered on the front end
    the image will be rendered via a different means (extract the PK from the
    URL, then render it in a bunch of sizes). We don't want to do that in the
    admin because it's quite expensive the first time.
    '''
    def get_redirect_url(self, *args, **kwargs):
        return PostImage.objects.get(pk=self.kwargs['pk']).image.url


class ImageUploadView(LoginRequiredMixin, FormView):
    '''
    A replacement for MarkdownX's upload view. Rather than saving it directly
    to storage, it will store it to the PostImage model.
    '''
    form_class = ImageUploadForm

    def form_invalid(self, form):
        response = JsonResponse({
            'image': 'Image missing or broken.',
        })
        response.status_code = 400
        return response

    def form_valid(self, form):
        form.save()
        return JsonResponse({
            'image_code': f'![]({form.instance.get_absolute_url()})'
        })

exhaust/posts/templates/posts/post_category_list.html
{% extends 'posts/post_list.html' %}

{% load markdown %}
{% load rss %}

{% block title %}
  {% if object.seo_title %}
    {{ object.seo_title}}
  {% else %}
    Category: {{ object}}
  {% endif %}
{% endblock %}

{% block feed_url %}
  {% url 'posts:post_category_feed' category=object.slug as feed_url %}
  <link rel="alternate" type="application/rss+xml" href="{{ feed_url|path_to_url }}" />
{% endblock %}

{% block canonical_url %}
  <link rel="canonical" href="{{ object.get_absolute_url|path_to_url }}">
{% endblock %}

{% block meta %}
  {{ block.super }}

  {% if object.meta_description %}
    <meta name="description" content="{{ object.meta_description }}">
  {% endif %}
{% endblock %}

{% block above_list %}
  <header class="article-list__header">
    <h1 class="article-list__title">
      Posts filed under &ldquo;{{ object }}&rdquo;

      {% if page_obj.number > 1 %}(page {{ page_obj.number }}){% endif %}
    </h1>

    {% if object.description %}
      <div class="article-list__description">
        <div class="markdown">
          {{ object.description|markdown }}

          <p>
            {% url 'posts:post_category_feed' category=object.slug as feed_url %}
            <a href="{{ feed_url }}">RSS feed for this category</a>
          </p>
        </div>
      </div>
    {% endif %}
  </header>
{% endblock %}

exhaust/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load rss %}

{% block title %}{% if object.seo_title %}{{ object.seo_title }}{% else %}{{ object }}{% endif %}{% endblock %}

{% block meta %}
  <link rel="canonical" href="{{ object.get_absolute_url|path_to_url }}">

  {% if object.meta_description %}
    <meta name="description" content="{{ object.meta_description }}">
  {% endif %}

  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ object.get_absolute_url|path_to_url }}">
  {% if object.title or object.opengraph_title %}
    <meta property="og:title" content="{% if object.opengraph_title %}{{ object.opengraph_title }}{% else %}{{ object.title }}{% endif %}">
  {% endif %}

  {% if object.meta_description or object.opengraph_description %}
    <meta property="og:description" content="{% if object.opengraph_description %}{{ object.opengraph_description }}{% else %}{{ object.meta_description }}{% endif %}">
  {% endif %}

  {% if object.image or object.opengraph_image %}
    <meta property="og:image" content="{% if object.opengraph_image %}{{ object.opengraph_image.url|path_to_url }}{% else %}{{ object.image.url|path_to_url }}{% endif %}">
  {% endif %}
{% endblock %}

{% block main %}
  {% include post.body_template %}
{% endblock %}

exhaust/posts/templates/posts/post_feed.html
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:atom="http://www.w3.org/2005/Atom"
  >
{% load rss %}
  <channel>
    <title>{{ feed_title }}</title>
    <description>{{ settings.SITE_DESCRIPTION }}</description>
    <link>{{ '/'|path_to_url }}</link>
    <language>en-GB</language>
    {% url 'posts:post_feed' as feed_url %}
    <atom:link href="{{ feed_url|path_to_url }}" rel="self" type="application/rss+xml" />

    {% for object in object_list %}
      <item>
        <title>{{ object }}</title>
        <link>{{ object.get_absolute_url|path_to_url }}</link>
        {% url 'posts:post_detail' identifier=object.identifier as guid_url %}
        <guid>{{ guid_url|path_to_url }}</guid>
        <pubDate>{{ object.date|format_rfc2822 }}</pubDate>
        <description>{% if object.meta_description %}{{ object.meta_description }}{% endif %}</description>

        <content:encoded>
          <![CDATA[
          {% rss_post_body object %}
          ]]>
        </content:encoded>
      </item>
    {% endfor %}
  </channel>
</rss>

exhaust/posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% load pagination %}
{% load rss %}

{% block meta %}
  {{ block.super }}

  {% block feed_url %}
    {{ feed_url }}
    <link rel="alternate" type="application/rss+xml" href="{{ feed_url|path_to_url }}" />
  {% endblock %}

  {% block canonical_url %}
    <link rel="canonical" href="{{ request.path|path_to_url }}" />
  {% endblock %}
{% endblock %}

{% block main %}
  <div class="article-list">
    {% block above_list %}{% endblock %}
    <div class="article-list__items">
      {% for object in object_list %}
        <div class="article-list__item">
          {% include object.body_template with detail_page=False %}
        </div>
      {% endfor %}
    </div>

    {% if page_obj and page_obj.has_other_pages %}
      <div class="article-list__paginator">
        <nav class="paginator">
          {% if page_obj.has_next %}
            <div class="paginator__item paginator__item--next">
              <a rel="next" href="{% pagination_url page_obj.next_page_number %}" class="paginator__link">&lt; Older posts</a>
            </div>
          {% endif %}

          {% if page_obj.has_previous %}
            <div class="paginator__item paginator__item--previous">
              <a rel="prev" href="{% pagination_url page_obj.previous_page_number %}" class="paginator__link">Newer posts &gt;</a>
            </div>
          {% endif %}
        </nav>
      </div>
    {% endif %}
  </div>
{% endblock %}

exhaust/posts/templates/posts/post_rss_item.html
{% extends object.body_template %}

{% block header %}{% endblock %}
{% block footer %}{% endblock %}